name: mediterm_dictionary
description: "Medical Dictionary App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  google_fonts:
  http:
  shared_preferences: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/medical-icon.png
    - assets/vintage-anatomy.jpg