name: mediterm_dictionary
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  http:
  shared_preferences: ^2.0.10
  audioplayers:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/medical-book-heart.jpg
    - assets/vintage-anatomy.jpg
    - assets/medical-desk.jpg